Repository kimtjrgus/Salog, pull requests merged in 2023-12, with the labels that each got.

#72 feat : 페이지 설정 로직 추가
  server/src/main/java/com/codemouse/salog/dto/MultiResponseDto.java
  server/src/main/java/com/codemouse/salog/dto/PageInfo.java
  server/src/main/java/com/codemouse/salog/dto/SingleResponseDto.java
Labels: 컴포넌트, 백엔드

#73 Feat : 일기 페이지 목업
  .DS_Store
  .vscode/settings.json
  client/db.json
  client/package-lock.json
  client/package.json
  client/src/assets/NotData.png
  client/src/assets/Test.jpeg
  client/src/components/Layout/MainLayout.tsx
  client/src/pages/dashboard/index.tsx
  client/src/pages/diary/index.tsx
  client/src/pages/login/index.tsx
  client/src/pages/sign_up/index.tsx
  client/src/utils/cookie.ts
Labels: 페이지, 프론트엔드

#77 Feat : 일기 작성 페이지 목업 및 일부 기능구현
  client/db.json
  client/src/App.tsx
  client/src/pages/diary/index.tsx
  client/src/pages/diary_write/index.tsx
  client/src/utils/dateAsKor.ts
Labels: 페이지, 기능, 프론트엔드

#79 Dev/be - jwt/회원 관련 전체 업데이트
  server/src/main/java/com/codemouse/salog/advice/GlobalExceptionAdvice.java
  server/src/main/java/com/codemouse/salog/auth/config/CustomCorsConfiguration.java
  server/src/main/java/com/codemouse/salog/auth/config/SecurityConfiguration.java
  server/src/main/java/com/codemouse/salog/auth/dto/LoginDto.java
  server/src/main/java/com/codemouse/salog/auth/filter/JwtAuthenticationFilter.java
  server/src/main/java/com/codemouse/salog/auth/filter/JwtVerificationFilter.java
  server/src/main/java/com/codemouse/salog/auth/handler/MemberAccessDeniedHandler.java
  server/src/main/java/com/codemouse/salog/auth/handler/MemberAuthenticationEntryPoint.java
  server/src/main/java/com/codemouse/salog/auth/handler/MemberAuthenticationFailureHandler.java
  server/src/main/java/com/codemouse/salog/auth/handler/MemberAuthenticationSuccessHandler.java
  server/src/main/java/com/codemouse/salog/auth/jwt/JwtTokenizer.java
  server/src/main/java/com/codemouse/salog/auth/userdetails/MemberDetailsService.java
  server/src/main/java/com/codemouse/salog/auth/utils/CustomAuthorityUtils.java
  server/src/main/java/com/codemouse/salog/auth/utils/ErrorResponder.java
  server/src/main/java/com/codemouse/salog/exception/BusinessLogicException.java
  server/src/main/java/com/codemouse/salog/exception/ExceptionCode.java
  server/src/main/java/com/codemouse/salog/members/controller/MemberController.java
  server/src/main/java/com/codemouse/salog/members/dto/MemberDto.java
  server/src/main/java/com/codemouse/salog/members/entity/Member.java
  server/src/main/java/com/codemouse/salog/members/mapper/MemberMapper.java
  server/src/main/java/com/codemouse/salog/members/repository/MemberRepository.java
  server/src/main/java/com/codemouse/salog/members/service/MemberService.java
  server/src/main/java/com/codemouse/salog/response/ErrorResponse.java
Labels: 기능, 백엔드

#81 Feat : 모달, 토스트 공용 컴포넌트 제작
  client/db.json
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/components/Layout/Modal.tsx
  client/src/components/Layout/Toast.tsx
  client/src/pages/diary/index.tsx
  client/src/pages/diary_write/index.tsx
  client/src/pages/diary_write/textEditor.tsx
Labels: 컴포넌트, 프론트엔드

#83 !HOTFIX : 회원 인코더, 디테일서비스, 서비스 로직 변경완료
  server/src/main/java/com/codemouse/salog/auth/userdetails/MemberDetailsService.java
  server/src/main/java/com/codemouse/salog/members/controller/MemberController.java
  server/src/main/java/com/codemouse/salog/members/service/MemberService.java
Labels: bug

#90 feat : Diary 기능/ Diary관련 Tag기능 전반 구현
  server/src/main/java/com/codemouse/salog/diary/controller/DiaryController.java
  server/src/main/java/com/codemouse/salog/diary/dto/DiaryDto.java
  server/src/main/java/com/codemouse/salog/diary/entity/Diary.java
  server/src/main/java/com/codemouse/salog/diary/mapper/DiaryMapper.java
  server/src/main/java/com/codemouse/salog/diary/repository/DiaryRepository.java
  server/src/main/java/com/codemouse/salog/diary/service/DiaryService.java
  server/src/main/java/com/codemouse/salog/exception/ExceptionCode.java
  server/src/main/java/com/codemouse/salog/tags/controller/TagController.java
  server/src/main/java/com/codemouse/salog/tags/dto/TagDto.java
  server/src/main/java/com/codemouse/salog/tags/entity/DiaryTag.java
  server/src/main/java/com/codemouse/salog/tags/entity/DiaryTagLink.java
  server/src/main/java/com/codemouse/salog/tags/mapper/TagMapper.java
  server/src/main/java/com/codemouse/salog/tags/repository/DiaryTagLinkRepository.java
  server/src/main/java/com/codemouse/salog/tags/repository/DiaryTagRepository.java
  server/src/main/java/com/codemouse/salog/tags/service/TagService.java
Labels: 기능, 백엔드

#93 feat & fix : 불필요한 로직 삭제, 회원 유효성 검증 추가
  .github/ISSUE_TEMPLATE/salog-issue-templates.md
  server/src/main/java/com/codemouse/salog/SalogApplication.java
  server/src/main/java/com/codemouse/salog/auth/dto/LoginDto.java
  server/src/main/java/com/codemouse/salog/exception/ExceptionCode.java
  server/src/main/java/com/codemouse/salog/members/controller/MemberController.java
  server/src/main/java/com/codemouse/salog/members/dto/EmailRequestDto.java
  server/src/main/java/com/codemouse/salog/members/dto/MemberDto.java
Labels: 기능, 백엔드

#94 Dev/be : 로그아웃 기능 추가
  server/src/main/java/com/codemouse/salog/auth/config/SecurityConfiguration.java
  server/src/main/java/com/codemouse/salog/auth/utils/TokenBlackListService.java
  server/src/main/java/com/codemouse/salog/exception/ExceptionCode.java
  server/src/main/java/com/codemouse/salog/members/controller/MemberController.java
Labels: 기능, 컴포넌트, 백엔드

#96 feat : jwt 리프레쉬 토큰을 바탕으로 검증 후 액세스 토큰 재발급 기능 추가 / 유효하지 않은 토큰 예외 추가
  server/src/main/java/com/codemouse/salog/auth/controller/TokenController.java
  server/src/main/java/com/codemouse/salog/auth/jwt/JwtTokenizer.java
  server/src/main/java/com/codemouse/salog/exception/ExceptionCode.java
  server/src/main/java/com/codemouse/salog/members/repository/MemberRepository.java
Labels: 기능, 백엔드

#97 refactor : Diary Response시 TagId 추가/ 로그아웃검증 로직 추가
  server/src/main/java/com/codemouse/salog/diary/dto/DiaryDto.java
  server/src/main/java/com/codemouse/salog/diary/entity/Diary.java
  server/src/main/java/com/codemouse/salog/diary/service/DiaryService.java
  server/src/main/java/com/codemouse/salog/tags/service/TagService.java
Labels: 백엔드

#101 Dev/be - 토큰 재발급 리팩터링
  server/src/main/java/com/codemouse/salog/auth/controller/TokenController.java
  server/src/main/java/com/codemouse/salog/auth/jwt/JwtTokenizer.java
  server/src/main/java/com/codemouse/salog/auth/utils/TokenBlackListService.java
  server/src/main/java/com/codemouse/salog/members/controller/MemberController.java
Labels: 백엔드

#103 feat : 가계부 : 수입 패키징
  server/src/main/java/com/codemouse/salog/ledger/income/controller/IncomeController.java
  server/src/main/java/com/codemouse/salog/ledger/income/dto/IncomeDto.java
  server/src/main/java/com/codemouse/salog/ledger/income/entity/Income.java
  server/src/main/java/com/codemouse/salog/ledger/income/mapper/IncomeMapper.java
  server/src/main/java/com/codemouse/salog/ledger/income/repository/IncomeRepository.java
  server/src/main/java/com/codemouse/salog/ledger/income/service/IncomeService.java
Labels: 백엔드

#105 fix : 태그,제목검색, 한글 입력시 UTF-8 디코딩 로직 추가
  server/src/main/java/com/codemouse/salog/diary/controller/DiaryController.java
  server/src/main/java/com/codemouse/salog/diary/service/DiaryService.java
Labels: bug

#106 ref/fix : 토큰재발급 및 블랙리스트 검증 리팩토링/ 일기 태그,제목검색 버그 수정
  server/src/main/java/com/codemouse/salog/auth/controller/TokenController.java
  server/src/main/java/com/codemouse/salog/auth/jwt/JwtTokenizer.java
  server/src/main/java/com/codemouse/salog/auth/utils/TokenBlackListService.java
  server/src/main/java/com/codemouse/salog/diary/controller/DiaryController.java
  server/src/main/java/com/codemouse/salog/diary/service/DiaryService.java
  server/src/main/java/com/codemouse/salog/ledger/income/controller/IncomeController.java
  server/src/main/java/com/codemouse/salog/ledger/income/dto/IncomeDto.java
  server/src/main/java/com/codemouse/salog/ledger/income/entity/Income.java
  server/src/main/java/com/codemouse/salog/ledger/income/mapper/IncomeMapper.java
  server/src/main/java/com/codemouse/salog/ledger/income/repository/IncomeRepository.java
  server/src/main/java/com/codemouse/salog/ledger/income/service/IncomeService.java
  server/src/main/java/com/codemouse/salog/members/controller/MemberController.java
Labels: bug, 기능, 백엔드

#108 feat/fix : 일기태그 유효성 검사 추가/ 일기 태그,제목검색 버그수정
  server/src/main/java/com/codemouse/salog/diary/controller/DiaryController.java
  server/src/main/java/com/codemouse/salog/diary/service/DiaryService.java
  server/src/main/java/com/codemouse/salog/exception/ExceptionCode.java
  server/src/main/java/com/codemouse/salog/tags/dto/TagDto.java
Labels: bug, 기능, 백엔드

#110 fix/feat : 일기태그, 제목검색 버그수정 및 일기태그 유효성검사 추가
  server/src/main/java/com/codemouse/salog/diary/controller/DiaryController.java
  server/src/main/java/com/codemouse/salog/diary/service/DiaryService.java
  server/src/main/java/com/codemouse/salog/exception/ExceptionCode.java
  server/src/main/java/com/codemouse/salog/tags/dto/TagDto.java
Labels: bug, 기능, 백엔드

#113 !HOTFIX : 회원 로그인 시 에러 리턴 분기 (상세하게)
  server/src/main/java/com/codemouse/salog/auth/handler/MemberAuthenticationFailureHandler.java
Labels: 기능, 백엔드

#116 feat : 일기, 태그검증로직 에러코드 수정/ 일기 유효성 검사 추가
  server/src/main/java/com/codemouse/salog/diary/dto/DiaryDto.java
  server/src/main/java/com/codemouse/salog/diary/entity/Diary.java
  server/src/main/java/com/codemouse/salog/diary/service/DiaryService.java
  server/src/main/java/com/codemouse/salog/exception/ExceptionCode.java
  server/src/main/java/com/codemouse/salog/tags/dto/TagDto.java
  server/src/main/java/com/codemouse/salog/tags/service/TagService.java
Labels: bug, invalid, 백엔드

#117 feat : 일기, 태그검증로직 에러코드 수정/ 일기 유효성 검사 추가
  server/src/main/java/com/codemouse/salog/diary/dto/DiaryDto.java
  server/src/main/java/com/codemouse/salog/diary/entity/Diary.java
  server/src/main/java/com/codemouse/salog/diary/service/DiaryService.java
  server/src/main/java/com/codemouse/salog/exception/ExceptionCode.java
  server/src/main/java/com/codemouse/salog/tags/dto/TagDto.java
  server/src/main/java/com/codemouse/salog/tags/service/TagService.java
Labels: invalid, 백엔드
