Repository kimtjrgus/Salog, pull requests merged in 2023-11, with the labels that each got.

#56 fix : prettier & eslint 에러 해결
  .github/ISSUE_TEMPLATE/salog-issue-templates.md
  .github/Pull_requsests_TEMPLATE.md
  client/.eslintignore
  client/.eslintrc.json
  client/.gitignore
  client/.prettierignore
  client/package-lock.json
  client/package.json
  client/prettierrc.json
  client/public/favicon.ico
  client/public/index.html
  client/public/logo192.png
  client/public/logo512.png
  client/public/manifest.json
  client/public/robots.txt
  client/src/.DS_Store
  client/src/App.css
  client/src/App.test.tsx
  client/src/App.tsx
  client/src/components/Layout/Header.tsx
  client/src/components/Layout/MainLayout.tsx
  client/src/components/Layout/SideBar.tsx
  client/src/fonts/.DS_Store
  client/src/fonts/Pretendard-Black.otf
  client/src/fonts/Pretendard-Bold.otf
  client/src/fonts/Pretendard-ExtraBold.otf
  client/src/fonts/Pretendard-ExtraLight.otf
  client/src/fonts/Pretendard-Light.otf
  client/src/fonts/Pretendard-Medium.otf
  client/src/fonts/Pretendard-Regular.otf
  client/src/fonts/Pretendard-SemiBold.otf
  client/src/fonts/Pretendard-Thin.otf
  client/src/fonts/Raleway-Bold.ttf
  client/src/index.tsx
  client/src/logo.svg
  client/src/pages/dashboard/index.tsx
  client/src/pages/diary/index.tsx
  client/src/pages/imcome_outgo/index.tsx
  client/src/react-app-env.d.ts
  client/src/reportWebVitals.ts
  client/src/service-worker.ts
  client/src/serviceWorkerRegistration.ts
  client/src/setupTests.ts
  client/src/store/index.ts
  client/src/store/slices/exampleSlice.ts
  client/src/styles/GlobalStyle.ts
  client/src/styles/Theme.ts
  client/tsconfig.json
Labels: bug, 프론트엔드

#60 Feat : 회원 기능 구조 전반 (JWT 별개, 세부 기능 별개) 구현
  server/.gitignore
  server/src/main/java/com/codemouse/salog/audit/Auditable.java
  server/src/main/java/com/codemouse/salog/members/controller/MemberController.java
  server/src/main/java/com/codemouse/salog/members/dto/MemberDto.java
  server/src/main/java/com/codemouse/salog/members/entity/Member.java
  server/src/main/java/com/codemouse/salog/members/mapper/MemberMapper.java
  server/src/main/java/com/codemouse/salog/members/repository/MemberRepository.java
  server/src/main/java/com/codemouse/salog/members/service/MemberService.java
Labels: 기능, 백엔드

#63 Feat : 로그인 / 회원가입 페이지 목업
  client/.eslintrc.json
  client/public/favicon.ico
  client/public/logo.png
  client/public/logo192.png
  client/public/logo512.png
  client/public/manifest.json
  client/src/App.tsx
  client/src/assets/Google.svg
  client/src/assets/Kakao.svg
  client/src/assets/Naver.svg
  client/src/assets/Slogo.png
  client/src/assets/Slogo.svg
  client/src/components/Layout/Header.tsx
  client/src/components/Layout/MainLayout.tsx
  client/src/components/Layout/SideBar.tsx
  client/src/hooks/useDebounce.ts
  client/src/index.tsx
  client/src/pages/login/index.tsx
  client/src/pages/sign_up/index.tsx
  client/src/reportWebVitals.ts
  client/src/service-worker.ts
  client/src/serviceWorkerRegistration.ts
  client/src/store/index.ts
  client/src/styles/Theme.ts
Labels: 페이지, 컴포넌트
