Repository kimtjrgus/Salog, pull requests merged in 2024-03, with the labels that each got.

#245 feat : 영수증 ocr을 이용한 지출 자동등록 기능
  server/src/main/java/com/codemouse/salog/helper/naverOcr/ClovaOcrApiService.java
  server/src/main/java/com/codemouse/salog/helper/naverOcr/ClovaOcrDto.java
  server/src/main/java/com/codemouse/salog/ledger/outgo/controller/OutgoController.java
  server/src/main/java/com/codemouse/salog/ledger/outgo/dto/OutgoDto.java
  server/src/main/java/com/codemouse/salog/ledger/outgo/service/OutgoService.java
Labels: 기능, 백엔드

#254 Dev/be : 불필요한 주석 삭제 / 회원 탈퇴시 상태변경 → 삭제로 변경 / 회원 상태 관련 로직 주석처리
  server/src/main/java/com/codemouse/salog/auth/config/SecurityConfiguration.java
  server/src/main/java/com/codemouse/salog/auth/filter/JwtAuthenticationFilter.java
  server/src/main/java/com/codemouse/salog/members/controller/MemberController.java
  server/src/main/java/com/codemouse/salog/members/entity/Member.java
  server/src/main/java/com/codemouse/salog/members/service/MemberService.java
  server/src/main/java/com/codemouse/salog/tags/ledgerTags/entity/LedgerTag.java
Labels: 기능, 백엔드

#260 feat : 설정 & 문의 페이지 제작
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/assets/Rolling-1s-21px.gif
  client/src/assets/Rolling2-1s-21px.gif
  client/src/components/Layout/Header.tsx
  client/src/components/Layout/ScheduleModal.tsx
  client/src/components/Layout/SideBar.tsx
  client/src/pages/account_setting/index.tsx
  client/src/pages/fixed_account/index.tsx
  client/src/pages/income_outgo/LedgerWrite.tsx
  client/src/pages/income_outgo/UpdateModal.tsx
  client/src/pages/income_outgo/index.tsx
  client/src/pages/inquiry/index.tsx
  client/src/pages/login/Google.tsx
  client/src/pages/login/index.tsx
  client/src/pages/monthChart/CustomTooltip.tsx
  client/src/pages/monthChart/PieChart.tsx
  client/src/pages/monthChart/index.tsx
  client/src/pages/password/index.tsx
  client/src/pages/sign_up/index.tsx
  client/src/store/index.ts
  client/src/store/slices/userSlice.ts
  client/src/utils/validCheck.ts
Labels: 페이지, 기능, 프론트엔드

#262 feat : 영수증 인식 기능
  client/package.json
  client/public/index.html
  client/src/components/Layout/ReceiptModal.tsx
  client/src/pages/dashboard/ReadModal.tsx
  client/src/pages/dashboard/WriteModal.tsx
  client/src/pages/dashboard/index.tsx
  client/src/pages/income_outgo/History.tsx
  client/src/pages/income_outgo/IncomeList.tsx
  client/src/pages/income_outgo/LedgerWrite.tsx
  client/src/pages/income_outgo/OutgoList.tsx
  client/src/pages/income_outgo/ReceiptCheckModal.tsx
  client/src/pages/income_outgo/index.tsx
  client/src/pages/login/index.tsx
Labels: 기능, 프론트엔드
