Repository kimtjrgus/Salog, pull requests merged in 2024-02, with the labels that each got.

#193 feat : diaryTagList 조회 시 일기 개수 필드 추가
  server/src/main/java/com/codemouse/salog/tags/diaryTags/controller/DiaryTagController.java
  server/src/main/java/com/codemouse/salog/tags/diaryTags/dto/DiaryTagDto.java
  server/src/main/java/com/codemouse/salog/tags/diaryTags/repository/DiaryTagLinkRepository.java
  server/src/main/java/com/codemouse/salog/tags/diaryTags/service/DiaryTagService.java
Labels: 기능, 백엔드

#197 feat : 일기 페이지 리팩토링
  .vscode/settings.json
  client/.eslintrc.json
  client/.firebaserc
  client/.gitignore
  client/@tomickigrzegorz__react-circular-progress-bar.d.ts
  client/firebase.json
  client/package-lock.json
  client/package.json
  client/public/favicon-16x16.png
  client/public/favicon-32x32.png
  client/public/favicon.ico
  client/public/index.html
  client/public/logo192.png
  client/public/logo512.png
  client/public/manifest.json
  client/public/maskable_icon.png
  client/src/App.tsx
  client/src/assets/Ellipsis-1.4s-200px.gif
  client/src/components/Layout/Loading.tsx
  client/src/components/Layout/MainLayout.tsx
  client/src/firebase.js
  client/src/hooks/useIntersectionObserver.ts
  client/src/pages/budget/index.tsx
  client/src/pages/dashboard/PieChart.tsx
  client/src/pages/dashboard/ReadModal.tsx
  client/src/pages/diary/Calendar.tsx
  client/src/pages/diary/index.tsx
  client/src/pages/diary_detail/index.tsx
  client/src/pages/diary_update/index.tsx
  client/src/pages/diary_write/index.tsx
  client/src/pages/diary_write/textEditor.tsx
  client/src/pages/income_outgo/History.tsx
  client/src/pages/income_outgo/IncomeList.tsx
  client/src/pages/income_outgo/OutgoList.tsx
  client/src/pages/income_outgo/UpdateModal.tsx
  client/src/pages/income_outgo/WasteList.tsx
  client/src/pages/income_outgo/index.tsx
  client/src/pages/monthChart/CustomTooltip.tsx
  client/src/pages/monthChart/PieChart.tsx
  client/src/pages/monthChart/index.tsx
  client/src/pages/password/index.tsx
  client/src/service-worker.ts
  client/storage.rules
Labels: 기능, 프론트엔드

#208 style : 반응형 일부 구현
  client/.eslintrc.json
  client/db.json
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/src/App.tsx
  client/src/assets/landing1.png
  client/src/assets/landing2.png
  client/src/assets/landing3.png
  client/src/assets/landing4.png
  client/src/components/Layout/Header.tsx
  client/src/components/Layout/MainLayout.tsx
  client/src/components/Layout/SideBar.tsx
  client/src/pages/budget/Modal.tsx
  client/src/pages/budget/index.tsx
  client/src/pages/dashboard/Calendar.tsx
  client/src/pages/dashboard/PieChart.tsx
  client/src/pages/dashboard/ReadModal.tsx
  client/src/pages/dashboard/Schedule.tsx
  client/src/pages/dashboard/WriteModal.tsx
  client/src/pages/dashboard/index.tsx
  client/src/pages/diary/Calendar.tsx
  client/src/pages/diary/index.tsx
  client/src/pages/diary_detail/index.tsx
  client/src/pages/diary_update/index.tsx
  client/src/pages/diary_write/index.tsx
  client/src/pages/fixed_account/index.tsx
  client/src/pages/income_outgo/History.tsx
  client/src/pages/income_outgo/IncomeList.tsx
  client/src/pages/income_outgo/LedgerWrite.tsx
  client/src/pages/income_outgo/OutgoList.tsx
  client/src/pages/income_outgo/UpdateModal.tsx
  client/src/pages/income_outgo/WasteList.tsx
  client/src/pages/income_outgo/index.tsx
  client/src/pages/landing/index.tsx
  client/src/pages/login/index.tsx
  client/src/pages/monthChart/CustomTooltip.tsx
  client/src/pages/monthChart/PieChart.tsx
  client/src/pages/monthChart/index.tsx
  client/src/pages/sign_up/index.tsx
  client/src/react-app-env.d.ts
  client/src/styles/GlobalStyle.ts
  client/src/styles/Theme.ts
  client/src/utils/refreshToken.tsx
  client/tsconfig.json
Labels: 페이지, 프론트엔드

#206 feat : diaryCalendar 조회 기능 추가, diary Delete 버그 수정 및 일부 리팩토링
  server/src/main/java/com/codemouse/salog/diary/controller/DiaryController.java
  server/src/main/java/com/codemouse/salog/diary/dto/DiaryDto.java
  server/src/main/java/com/codemouse/salog/diary/repository/DiaryRepository.java
  server/src/main/java/com/codemouse/salog/diary/service/DiaryService.java
  server/src/main/java/com/codemouse/salog/tags/diaryTags/repository/DiaryTagLinkRepository.java
  server/src/main/java/com/codemouse/salog/tags/diaryTags/service/DiaryTagService.java
Labels: bug, 기능, 백엔드

#209 feat : 웹 알림 기능 추가
  client/src/App.tsx
  client/src/components/Layout/Header.tsx
  client/src/index.tsx
  client/src/pages/dashboard/Calendar.tsx
  client/src/pages/dashboard/Schedule.tsx
  client/src/pages/dashboard/index.tsx
  client/src/pages/diary/Calendar.tsx
  client/src/pages/diary/index.tsx
  client/src/pages/diary_detail/index.tsx
  client/src/pages/diary_update/index.tsx
  client/src/pages/diary_write/textEditor.tsx
  client/src/pages/fixed_account/index.tsx
  client/src/pages/income_outgo/LedgerWrite.tsx
  client/src/pages/income_outgo/index.tsx
  client/src/pages/login/index.tsx
  client/src/store/index.ts
  client/src/store/slices/scheduleSlice.ts
  client/src/styles/GlobalStyle.ts
  client/src/utils/circulateSchedule.ts
  client/src/utils/refreshToken.ts
  client/src/utils/refreshToken.tsx
Labels: 기능, 프론트엔드

#212 feat : 캘린더 수입지출 통합조회 기능 추가
  server/src/main/java/com/codemouse/salog/ledger/calendar/controller/CalendarController.java
  server/src/main/java/com/codemouse/salog/ledger/calendar/dto/CalendarDto.java
  server/src/main/java/com/codemouse/salog/ledger/calendar/service/CalendarService.java
  server/src/main/java/com/codemouse/salog/ledger/outgo/service/OutgoService.java
Labels: 기능, 백엔드

#213 feat : 캘린더 수입지출 통합조회 기능 추가
  server/src/main/java/com/codemouse/salog/ledger/calendar/controller/CalendarController.java
  server/src/main/java/com/codemouse/salog/ledger/calendar/dto/CalendarDto.java
  server/src/main/java/com/codemouse/salog/ledger/calendar/service/CalendarService.java
  server/src/main/java/com/codemouse/salog/ledger/outgo/service/OutgoService.java
Labels: 기능, 백엔드

#214 feat : 웹 알림 기능 추가
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/src/assets/landing2.png
  client/src/assets/landing3.png
  client/src/assets/landing4.png
  client/src/assets/landing5.png
  client/src/assets/landing6.png
  client/src/assets/landing7.png
  client/src/components/Layout/Header.tsx
  client/src/components/Layout/Paging.tsx
  client/src/components/Layout/ScheduleModal.tsx
  client/src/hooks/useDidMountEffect.ts
  client/src/pages/budget/index.tsx
  client/src/pages/dashboard/ReadModal.tsx
  client/src/pages/dashboard/Schedule.tsx
  client/src/pages/dashboard/index.tsx
  client/src/pages/diary_write/index.tsx
  client/src/pages/fixed_account/index.tsx
  client/src/pages/income_outgo/History.tsx
  client/src/pages/income_outgo/IncomeList.tsx
  client/src/pages/income_outgo/LedgerWrite.tsx
  client/src/pages/income_outgo/OutgoList.tsx
  client/src/pages/income_outgo/UpdateModal.tsx
  client/src/pages/income_outgo/WasteList.tsx
  client/src/pages/income_outgo/index.tsx
  client/src/pages/landing/index.tsx
  client/src/pages/login/index.tsx
  client/src/pages/monthChart/index.tsx
  client/src/utils/circulateSchedule.ts
  client/src/utils/circulateScheduleNow.ts
Labels: 페이지, 기능, 프론트엔드

#215 feat : Oauth2 (구글) 추가
  server/src/main/java/com/codemouse/salog/auth/config/SecurityConfiguration.java
  server/src/main/java/com/codemouse/salog/auth/controller/SecurityController.java
  server/src/main/java/com/codemouse/salog/exception/ExceptionCode.java
  server/src/main/java/com/codemouse/salog/members/controller/MemberController.java
  server/src/main/java/com/codemouse/salog/members/entity/Member.java
  server/src/main/java/com/codemouse/salog/members/service/MemberService.java
Labels: 기능, 백엔드

#219 feat : Oauth 서비스, 컨트롤러 분리 / Oauth 구현 완료
  server/src/main/java/com/codemouse/salog/auth/config/SecurityConfiguration.java
  server/src/main/java/com/codemouse/salog/auth/controller/OauthController.java
  server/src/main/java/com/codemouse/salog/auth/service/OauthService.java
  server/src/main/java/com/codemouse/salog/members/controller/MemberController.java
  server/src/main/java/com/codemouse/salog/members/service/MemberService.java
Labels: 기능, 백엔드
