Repository kimtjrgus/Salog, pull requests merged in 2024-01, with the labels that each got.

#128 feat : 가계부-지출 CRUD 작성 및 유효성 검증/ (태그, 일기관련 로직 미포함)
  server/src/main/java/com/codemouse/salog/exception/ExceptionCode.java
  server/src/main/java/com/codemouse/salog/ledger/outgo/controller/OutgoController.java
  server/src/main/java/com/codemouse/salog/ledger/outgo/dto/OutgoDto.java
  server/src/main/java/com/codemouse/salog/ledger/outgo/entity/Outgo.java
  server/src/main/java/com/codemouse/salog/ledger/outgo/mapper/OutgoMapper.java
  server/src/main/java/com/codemouse/salog/ledger/outgo/repository/OutgoRepository.java
  server/src/main/java/com/codemouse/salog/ledger/outgo/service/OutgoService.java
Labels: 기능, 백엔드

#129 feat : 수입, 지출 태그 완료
  server/src/main/java/com/codemouse/salog/diary/dto/DiaryDto.java
  server/src/main/java/com/codemouse/salog/diary/entity/Diary.java
  server/src/main/java/com/codemouse/salog/diary/service/DiaryService.java
  server/src/main/java/com/codemouse/salog/exception/ExceptionCode.java
  server/src/main/java/com/codemouse/salog/ledger/income/controller/IncomeController.java
  server/src/main/java/com/codemouse/salog/ledger/income/dto/IncomeDto.java
  server/src/main/java/com/codemouse/salog/ledger/income/entity/Income.java
  server/src/main/java/com/codemouse/salog/ledger/income/mapper/IncomeMapper.java
  server/src/main/java/com/codemouse/salog/ledger/income/repository/IncomeRepository.java
  server/src/main/java/com/codemouse/salog/ledger/income/service/IncomeService.java
  server/src/main/java/com/codemouse/salog/ledger/outgo/entity/Outgo.java
  server/src/main/java/com/codemouse/salog/ledger/outgo/service/OutgoService.java
  server/src/main/java/com/codemouse/salog/members/service/MemberService.java
  server/src/main/java/com/codemouse/salog/tags/diaryTags/controller/DiaryTagController.java
  server/src/main/java/com/codemouse/salog/tags/diaryTags/dto/DiaryTagDto.java
  server/src/main/java/com/codemouse/salog/tags/diaryTags/entity/DiaryTag.java
  server/src/main/java/com/codemouse/salog/tags/diaryTags/entity/DiaryTagLink.java
  server/src/main/java/com/codemouse/salog/tags/diaryTags/mapper/DiaryTagMapper.java
  server/src/main/java/com/codemouse/salog/tags/diaryTags/repository/DiaryTagLinkRepository.java
  server/src/main/java/com/codemouse/salog/tags/diaryTags/repository/DiaryTagRepository.java
  server/src/main/java/com/codemouse/salog/tags/diaryTags/service/DiaryTagService.java
  server/src/main/java/com/codemouse/salog/tags/ledgerTags/controller/LedgerTagController.java
  server/src/main/java/com/codemouse/salog/tags/ledgerTags/dto/LedgerTagDto.java
  server/src/main/java/com/codemouse/salog/tags/ledgerTags/entity/LedgerTag.java
  server/src/main/java/com/codemouse/salog/tags/ledgerTags/entity/LedgerTagLink.java
  server/src/main/java/com/codemouse/salog/tags/ledgerTags/mapper/LedgerTagMapper.java
  server/src/main/java/com/codemouse/salog/tags/ledgerTags/repository/LedgerTagLinkRepository.java
  server/src/main/java/com/codemouse/salog/tags/ledgerTags/repository/LedgerTagRepository.java
  server/src/main/java/com/codemouse/salog/tags/ledgerTags/service/LedgerTagService.java
  server/src/main/java/com/codemouse/salog/tags/mapper/TagMapper.java
Labels: 기능, 백엔드

#132 feat : 수입 서비스 태그 관련 로직 작성 완료
  server/src/main/java/com/codemouse/salog/auth/config/SecurityConfiguration.java
  server/src/main/java/com/codemouse/salog/ledger/income/controller/IncomeController.java
  server/src/main/java/com/codemouse/salog/ledger/income/dto/IncomeDto.java
  server/src/main/java/com/codemouse/salog/ledger/income/entity/Income.java
  server/src/main/java/com/codemouse/salog/ledger/income/repository/IncomeRepository.java
  server/src/main/java/com/codemouse/salog/ledger/income/service/IncomeService.java
  server/src/main/java/com/codemouse/salog/tags/ledgerTags/controller/LedgerTagController.java
  server/src/main/java/com/codemouse/salog/tags/ledgerTags/dto/LedgerTagDto.java
  server/src/main/java/com/codemouse/salog/tags/ledgerTags/entity/LedgerTag.java
  server/src/main/java/com/codemouse/salog/tags/ledgerTags/entity/LedgerTagLink.java
  server/src/main/java/com/codemouse/salog/tags/ledgerTags/repository/LedgerTagLinkRepository.java
  server/src/main/java/com/codemouse/salog/tags/ledgerTags/repository/LedgerTagRepository.java
  server/src/main/java/com/codemouse/salog/tags/ledgerTags/service/LedgerTagService.java
Labels: 기능, 백엔드

#135 feat : 가계부-지출 태그관련 로직 추가
  server/src/main/java/com/codemouse/salog/ledger/income/entity/Income.java
  server/src/main/java/com/codemouse/salog/ledger/outgo/dto/OutgoDto.java
  server/src/main/java/com/codemouse/salog/ledger/outgo/entity/Outgo.java
  server/src/main/java/com/codemouse/salog/ledger/outgo/mapper/OutgoMapper.java
  server/src/main/java/com/codemouse/salog/ledger/outgo/repository/OutgoRepository.java
  server/src/main/java/com/codemouse/salog/ledger/outgo/service/OutgoService.java
  server/src/main/java/com/codemouse/salog/tags/ledgerTags/dto/LedgerTagDto.java
  server/src/main/java/com/codemouse/salog/tags/ledgerTags/repository/LedgerTagRepository.java
Labels: 기능, 백엔드

#138 feat : 일기 페이지 완료 및 대시보드 페이지 작업
  client/package-lock.json
  client/package.json
  client/src/components/Layout/SideBar.tsx
  client/src/index.tsx
  client/src/pages/dashboard/Calendar.tsx
  client/src/pages/dashboard/PieChart.tsx
  client/src/pages/dashboard/Schedule.tsx
  client/src/pages/dashboard/WriteModal.tsx
  client/src/pages/dashboard/index.tsx
  client/src/pages/diary/index.tsx
  client/src/pages/diary_update/index.tsx
  client/src/pages/login/index.tsx
  client/src/store/index.ts
  client/src/store/slices/exampleSlice.ts
  client/src/store/slices/pieChartSlice.ts
  client/src/store/slices/userSlice.ts
  client/src/utils/refreshToken.ts
  client/src/utils/refreshToken.tsx
Labels: 페이지, 기능, 프론트엔드

#139 feat : 가계부-고정지출 CRUD 구현
  server/src/main/java/com/codemouse/salog/exception/ExceptionCode.java
  server/src/main/java/com/codemouse/salog/ledger/fixedOutgo/controller/FixedOutgoController.java
  server/src/main/java/com/codemouse/salog/ledger/fixedOutgo/dto/FixedOutgoDto.java
  server/src/main/java/com/codemouse/salog/ledger/fixedOutgo/entity/FixedOutgo.java
  server/src/main/java/com/codemouse/salog/ledger/fixedOutgo/mapper/FixedOutgoMapper.java
  server/src/main/java/com/codemouse/salog/ledger/fixedOutgo/repository/FixedOutgoRepository.java
  server/src/main/java/com/codemouse/salog/ledger/fixedOutgo/service/FixedOutgoService.java
Labels: 기능, 백엔드

#140 feat/fix : 지출 결제수단 컬럼 추가/ 수입,지출 태그관련 무결성 버그수정
  server/src/main/java/com/codemouse/salog/ledger/outgo/dto/OutgoDto.java
  server/src/main/java/com/codemouse/salog/ledger/outgo/entity/Outgo.java
  server/src/main/java/com/codemouse/salog/tags/ledgerTags/repository/LedgerTagRepository.java
  server/src/main/java/com/codemouse/salog/tags/ledgerTags/service/LedgerTagService.java
Labels: bug, 백엔드

#142 feat : 회원-태그 양방향 매핑 후 회원 조회 시 태그 출력
  server/src/main/java/com/codemouse/salog/ledger/income/dto/IncomeDto.java
  server/src/main/java/com/codemouse/salog/ledger/income/entity/Income.java
  server/src/main/java/com/codemouse/salog/ledger/income/service/IncomeService.java
  server/src/main/java/com/codemouse/salog/members/dto/MemberDto.java
  server/src/main/java/com/codemouse/salog/members/entity/Member.java
  server/src/main/java/com/codemouse/salog/members/mapper/MemberMapper.java
  server/src/main/java/com/codemouse/salog/tags/ledgerTags/dto/LedgerTagDto.java
Labels: 기능, 백엔드

#143 !HOTFIX : 수입, 지출 태그 동일 이름 시 충돌 에러 핸들링
  server/src/main/java/com/codemouse/salog/ledger/income/service/IncomeService.java
  server/src/main/java/com/codemouse/salog/ledger/outgo/service/OutgoService.java
  server/src/main/java/com/codemouse/salog/tags/ledgerTags/repository/LedgerTagRepository.java
  server/src/main/java/com/codemouse/salog/tags/ledgerTags/service/LedgerTagService.java
Labels: bug, 백엔드

#144 fix : 수입에서 "결제수단" 제거
  server/src/main/java/com/codemouse/salog/ledger/income/dto/IncomeDto.java
  server/src/main/java/com/codemouse/salog/ledger/income/entity/Income.java
  server/src/main/java/com/codemouse/salog/ledger/income/service/IncomeService.java
Labels: 기능, 백엔드

#146 feat : 대시보드 페이지 구현
  client/src/components/Layout/Header.tsx
  client/src/components/Layout/MainLayout.tsx
  client/src/pages/dashboard/Calendar.tsx
  client/src/pages/dashboard/ReadModal.tsx
  client/src/pages/dashboard/WriteModal.tsx
  client/src/pages/dashboard/index.tsx
  client/src/pages/diary/Calendar.tsx
Labels: 기능, 프론트엔드

#152 feat : 지출/수입 조회 페이지 목업
  client/db.json
  client/src/App.tsx
  client/src/components/Layout/SideBar.tsx
  client/src/pages/imcome_outgo/History.tsx
  client/src/pages/imcome_outgo/IncomeList.tsx
  client/src/pages/imcome_outgo/OutgoList.tsx
  client/src/pages/imcome_outgo/WasteList.tsx
  client/src/pages/imcome_outgo/index.tsx
  client/src/utils/scrollToTop.ts
Labels: 페이지, 프론트엔드

#154 Feat : 지출 - patchOutgo 로직 수정, 월별 지출통계 기능구현
  server/src/main/java/com/codemouse/salog/ledger/outgo/controller/OutgoController.java
  server/src/main/java/com/codemouse/salog/ledger/outgo/dto/OutgoDto.java
  server/src/main/java/com/codemouse/salog/ledger/outgo/mapper/OutgoMapper.java
  server/src/main/java/com/codemouse/salog/ledger/outgo/repository/OutgoRepository.java
  server/src/main/java/com/codemouse/salog/ledger/outgo/service/OutgoService.java
Labels: 기능, 백엔드

#155 Feat : 수입 - 월별 합계 계산 + 태그별 월 합계 계산 로직 구현 / 월간 예산 CRUD 구현 (월별 지출 합계 연결 X)
  server/src/main/java/com/codemouse/salog/exception/ExceptionCode.java
  server/src/main/java/com/codemouse/salog/ledger/budget/controller/BudgetController.java
  server/src/main/java/com/codemouse/salog/ledger/budget/dto/BudgetDto.java
  server/src/main/java/com/codemouse/salog/ledger/budget/entity/MonthlyBudget.java
  server/src/main/java/com/codemouse/salog/ledger/budget/mapper/BudgetMapper.java
  server/src/main/java/com/codemouse/salog/ledger/budget/repository/BudgetRepository.java
  server/src/main/java/com/codemouse/salog/ledger/budget/service/BudgetService.java
  server/src/main/java/com/codemouse/salog/ledger/income/controller/IncomeController.java
  server/src/main/java/com/codemouse/salog/ledger/income/dto/IncomeDto.java
  server/src/main/java/com/codemouse/salog/ledger/income/repository/IncomeRepository.java
  server/src/main/java/com/codemouse/salog/ledger/income/service/IncomeService.java
  server/src/main/java/com/codemouse/salog/tags/ledgerTags/dto/LedgerTagDto.java
Labels: 기능, 백엔드

#157 feat : 낭비리스트 조회 및 통계 구현(일부 리팩토링)
  server/src/main/java/com/codemouse/salog/ledger/income/dto/IncomeDto.java
  server/src/main/java/com/codemouse/salog/ledger/outgo/controller/OutgoController.java
  server/src/main/java/com/codemouse/salog/ledger/outgo/dto/OutgoDto.java
  server/src/main/java/com/codemouse/salog/ledger/outgo/repository/OutgoRepository.java
  server/src/main/java/com/codemouse/salog/ledger/outgo/service/OutgoService.java
Labels: 기능, 백엔드

#159 Feat : 월별 예산 구현 완료 / 수입 통계 수정
  server/src/main/java/com/codemouse/salog/ledger/budget/dto/BudgetDto.java
  server/src/main/java/com/codemouse/salog/ledger/budget/service/BudgetService.java
  server/src/main/java/com/codemouse/salog/ledger/income/repository/IncomeRepository.java
  server/src/main/java/com/codemouse/salog/ledger/income/service/IncomeService.java
  server/src/main/java/com/codemouse/salog/ledger/outgo/repository/OutgoRepository.java
Labels: 기능, 백엔드

#160 feat : 캘린더 조회 구현
  server/src/main/java/com/codemouse/salog/ledger/calendar/controller/CalendarController.java
  server/src/main/java/com/codemouse/salog/ledger/calendar/dto/CalendarDto.java
  server/src/main/java/com/codemouse/salog/ledger/calendar/service/CalendarService.java
  server/src/main/java/com/codemouse/salog/ledger/income/repository/IncomeRepository.java
  server/src/main/java/com/codemouse/salog/ledger/income/service/IncomeService.java
  server/src/main/java/com/codemouse/salog/ledger/outgo/repository/OutgoRepository.java
  server/src/main/java/com/codemouse/salog/ledger/outgo/service/OutgoService.java
Labels: 기능, 백엔드

#162 feat : 가계부 조회 및 고정 지출/수입
  client/src/components/Layout/SideBar.tsx
  client/src/pages/dashboard/Calendar.tsx
  client/src/pages/fixed_account/index.tsx
  client/src/pages/imcome_outgo/History.tsx
  client/src/pages/imcome_outgo/IncomeList.tsx
  client/src/pages/imcome_outgo/LedgerWrite.tsx
  client/src/pages/imcome_outgo/OutgoList.tsx
  client/src/pages/imcome_outgo/WasteList.tsx
  client/src/pages/imcome_outgo/index.tsx
  client/src/store/index.ts
  client/src/store/slices/toastSlice.ts
  client/src/store/slices/userSlice.ts
Labels: 페이지, 기능, 프론트엔드

#163 update : 전체 DTO 정규표현식 업데이트
  server/src/main/java/com/codemouse/salog/ledger/budget/dto/BudgetDto.java
  server/src/main/java/com/codemouse/salog/ledger/fixedIncome/dto/FixedIncomeDto.java
  server/src/main/java/com/codemouse/salog/ledger/fixedOutgo/dto/FixedOutgoDto.java
  server/src/main/java/com/codemouse/salog/ledger/income/dto/IncomeDto.java
Labels: 기능, 백엔드

#167 fix/feat - ledger patch 버그 수정/ post, patch시 응답 추가/ outgo 유효성 검사
  server/src/main/java/com/codemouse/salog/ledger/fixedIncome/controller/FixedIncomeController.java
  server/src/main/java/com/codemouse/salog/ledger/fixedIncome/service/FixedIncomeService.java
  server/src/main/java/com/codemouse/salog/ledger/fixedOutgo/controller/FixedOutgoController.java
  server/src/main/java/com/codemouse/salog/ledger/fixedOutgo/dto/FixedOutgoDto.java
  server/src/main/java/com/codemouse/salog/ledger/fixedOutgo/entity/FixedOutgo.java
  server/src/main/java/com/codemouse/salog/ledger/fixedOutgo/service/FixedOutgoService.java
  server/src/main/java/com/codemouse/salog/ledger/income/controller/IncomeController.java
  server/src/main/java/com/codemouse/salog/ledger/income/service/IncomeService.java
  server/src/main/java/com/codemouse/salog/ledger/outgo/controller/OutgoController.java
  server/src/main/java/com/codemouse/salog/ledger/outgo/dto/OutgoDto.java
  server/src/main/java/com/codemouse/salog/ledger/outgo/entity/Outgo.java
  server/src/main/java/com/codemouse/salog/ledger/outgo/service/OutgoService.java
Labels: bug, invalid, 기능, 백엔드

#177 feat : 예산 중복 등록 불가능, 값이 있는 경우 에러 응답
  server/src/main/java/com/codemouse/salog/exception/ExceptionCode.java
  server/src/main/java/com/codemouse/salog/ledger/budget/service/BudgetService.java
  server/src/main/java/com/codemouse/salog/ledger/income/dto/IncomeDto.java
  server/src/main/java/com/codemouse/salog/tags/ledgerTags/controller/LedgerTagController.java
  server/src/main/java/com/codemouse/salog/tags/ledgerTags/service/LedgerTagService.java
Labels: 백엔드
